# Generated by Django 4.0.3 on 2023-09-25 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0003_userinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='User_quota',
            field=models.PositiveIntegerField(default=15),
        ),
    ]
